import type { RepoFile } from '@/lib/github'
import {
  getFramework,
  packagesToRecord,
  type FrameworkId,
  type LanguageId,
  type PackageEntry,
} from '@/lib/frameworks'
import {
  generateShadcnFiles,
  mergeShadcnPackages,
  shadcnDemoComponent,
  shadcnDemoImports,
} from '@/lib/shadcn'

export type GenerateInput = {
  componentCode: string
  instructions?: string
  repoName?: string
  framework?: FrameworkId
  language?: LanguageId
  shadcn?: boolean
}

type GenCtx = {
  repoName: string
  componentName: string
  componentSource: string
  instructions: string
  language: LanguageId
  shadcn: boolean
}

function slugify(name: string) {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 40) || 'repcn-app'
  )
}

function extractComponentName(code: string): string {
  const named =
    code.match(/export\s+default\s+function\s+([A-Za-z0-9_]+)/)?.[1] ||
    code.match(/function\s+([A-Za-z0-9_]+)\s*\(/)?.[1] ||
    code.match(/const\s+([A-Za-z0-9_]+)\s*=/)?.[1]
  return named || 'GeneratedComponent'
}

function ensureDefaultExport(code: string, componentName: string): string {
  if (/export\s+default/.test(code)) return code.trim() + '\n'
  if (
    new RegExp(`function\\s+${componentName}\\b`).test(code) ||
    new RegExp(`const\\s+${componentName}\\b`).test(code)
  ) {
    return `${code.trim()}\n\nexport default ${componentName}\n`
  }
  return `${code.trim()}\n\nexport default function ${componentName}() {\n  return null\n}\n`
}

function commentBlock(instructions: string) {
  if (!instructions.trim()) return ''
  return `\n{/* Instructions: ${instructions.replace(/\*\//g, '* /')} */}\n`
}

function componentExt(language: LanguageId) {
  return language === 'js' ? 'jsx' : 'tsx'
}

function scriptExt(language: LanguageId) {
  return language === 'js' ? 'js' : 'ts'
}

function sharedTailwindFiles(
  language: LanguageId,
  contentGlobs: string[]
): RepoFile[] {
  const postcss: RepoFile = {
    path: 'postcss.config.mjs',
    content: `/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}

export default config
`,
  }

  if (language === 'js') {
    return [
      postcss,
      {
        path: 'tailwind.config.js',
        content: `/** @type {import('tailwindcss').Config} */
export default {
  content: ${JSON.stringify(contentGlobs, null, 2)},
  theme: {
    extend: {},
  },
  plugins: [],
}
`,
      },
    ]
  }

  return [
    postcss,
    {
      path: 'tailwind.config.ts',
      content: `import type { Config } from 'tailwindcss'

const config: Config = {
  content: ${JSON.stringify(contentGlobs, null, 2)},
  theme: {
    extend: {},
  },
  plugins: [],
}

export default config
`,
    },
  ]
}

function readme(
  repoName: string,
  frameworkLabel: string,
  language: LanguageId,
  instructions: string,
  runCommand: string,
  shadcn: boolean
): RepoFile {
  const langLabel = language === 'js' ? 'JavaScript' : 'TypeScript'
  const extHint = language === 'js' ? '.js / .jsx' : '.ts / .tsx'
  return {
    path: 'README.md',
    content: `# ${repoName}

Generated by RepCN as a **${frameworkLabel}** (${langLabel}) app from a React component.

File extensions: \`${extHint}\`
${shadcn ? '\nIncludes **shadcn/ui** with `Button` and `Input` under `components/ui`.\n' : ''}
${instructions ? `## Instructions\n\n${instructions}\n\n` : ''}## Run

\`\`\`bash
${runCommand}
\`\`\`
`,
  }
}

function pkgJson(
  repoName: string,
  packages: PackageEntry[],
  language: LanguageId,
  scripts: Record<string, string>,
  extra?: Record<string, unknown>
): RepoFile {
  return {
    path: 'package.json',
    content:
      JSON.stringify(
        {
          name: repoName,
          version: '0.1.0',
          private: true,
          ...extra,
          scripts,
          dependencies: packagesToRecord(packages, 'dependency', language),
          devDependencies: packagesToRecord(packages, 'devDependency', language),
        },
        null,
        2
      ) + '\n',
  }
}

function styleAndUiFiles(
  framework: FrameworkId,
  language: LanguageId,
  contentGlobs: string[],
  cssPath: string,
  plainCss: string,
  shadcn: boolean
): RepoFile[] {
  const postcss: RepoFile = {
    path: 'postcss.config.mjs',
    content: `/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}

export default config
`,
  }

  if (shadcn) {
    return [postcss, ...generateShadcnFiles({ framework, language, contentGlobs })]
  }

  return [
    ...sharedTailwindFiles(language, contentGlobs),
    { path: cssPath, content: plainCss },
  ]
}

function pageContent(opts: {
  language: LanguageId
  shadcn: boolean
  note: string
  componentName: string
  importLine: string
  fnName?: string
}): string {
  const fn = opts.fnName || 'HomePage'
  const imports = opts.shadcn
    ? `${shadcnDemoImports()}\n${opts.importLine}`
    : opts.importLine
  const helper = opts.shadcn ? `\n${shadcnDemoComponent()}\n` : '\n'
  const starter = opts.shadcn ? '      <ShadcnStarter />\n' : ''
  return `${imports}
${helper}export default function ${fn}() {
  return (
    <main className="mx-auto min-h-screen max-w-3xl p-6">
${starter}      ${opts.note}<${opts.componentName} />
    </main>
  )
}
`
}

const PLAIN_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  @apply min-h-screen bg-zinc-50 text-zinc-900 antialiased;
}
`

function generateNextjs(input: GenCtx): RepoFile[] {
  const meta = getFramework('nextjs')
  const {
    repoName,
    componentName,
    componentSource,
    instructions,
    language,
    shadcn,
  } = input
  const note = commentBlock(instructions)
  const cExt = componentExt(language)
  const packages = mergeShadcnPackages(meta.packages, shadcn)
  const contentGlobs = [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ]

  const files: RepoFile[] = [
    pkgJson(repoName, packages, language, {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    }),
  ]

  if (language === 'ts') {
    files.push(
      {
        path: 'tsconfig.json',
        content: `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`,
      },
      {
        path: 'next.config.ts',
        content: `import type { NextConfig } from 'next'

const nextConfig: NextConfig = {}

export default nextConfig
`,
      },
      {
        path: 'next-env.d.ts',
        content: `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`,
      }
    )
  } else {
    files.push(
      {
        path: 'jsconfig.json',
        content: `{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": { "@/*": ["./*"] }
  },
  "exclude": ["node_modules", ".next"]
}
`,
      },
      {
        path: 'next.config.mjs',
        content: `/** @type {import('next').NextConfig} */
const nextConfig = {}

export default nextConfig
`,
      }
    )
  }

  files.push(
    ...styleAndUiFiles(
      'nextjs',
      language,
      contentGlobs,
      'app/globals.css',
      PLAIN_CSS,
      shadcn
    ),
    {
      path: '.gitignore',
      content: `node_modules
.next
out
build
coverage
.DS_Store
*.pem
.env*
!.env.example
npm-debug.log*
yarn-debug.log*
yarn-error.log*
*.tsbuildinfo
next-env.d.ts
`,
    },
    readme(repoName, meta.label, language, instructions, meta.runCommand, shadcn),
    {
      path: `app/layout.${cExt}`,
      content:
        language === 'ts'
          ? `import type { Metadata } from 'next'
import { Toaster } from 'sonner'
import './globals.css'

export const metadata: Metadata = {
  title: '${repoName}',
  description: 'Generated by RepCN',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  )
}
`
          : `import { Toaster } from 'sonner'
import './globals.css'

export const metadata = {
  title: '${repoName}',
  description: 'Generated by RepCN',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  )
}
`,
    },
    {
      path: `app/page.${cExt}`,
      content: pageContent({
        language,
        shadcn,
        note,
        componentName,
        importLine: `import ${componentName} from '@/components/${componentName}'`,
      }),
    },
    {
      path: `components/${componentName}.${cExt}`,
      content: componentSource,
    }
  )

  return files
}

function generateVite(input: GenCtx): RepoFile[] {
  const meta = getFramework('vite')
  const {
    repoName,
    componentName,
    componentSource,
    instructions,
    language,
    shadcn,
  } = input
  const note = commentBlock(instructions)
  const cExt = componentExt(language)
  const sExt = scriptExt(language)
  const mainFile = `src/main.${cExt}`
  const packages = mergeShadcnPackages(meta.packages, shadcn)
  const contentGlobs = ['./index.html', './src/**/*.{js,ts,jsx,tsx}']

  const files: RepoFile[] = [
    pkgJson(
      repoName,
      packages,
      language,
      {
        dev: 'vite',
        build: language === 'ts' ? 'tsc -b && vite build' : 'vite build',
        preview: 'vite preview',
      },
      { type: 'module' }
    ),
  ]

  if (language === 'ts') {
    files.push(
      {
        path: 'tsconfig.json',
        content: `{
  "compilerOptions": {
    "target": "ES2022",
    "useDefineForClassFields": true,
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "baseUrl": ".",
    "paths": { "@/*": ["src/*"] }
  },
  "include": ["src"]
}
`,
      },
      {
        path: 'tsconfig.node.json',
        content: `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["ES2023"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler"
  },
  "include": ["vite.config.ts"]
}
`,
      },
      {
        path: 'src/vite-env.d.ts',
        content: `/// <reference types="vite/client" />
`,
      }
    )
  } else {
    files.push({
      path: 'jsconfig.json',
      content: `{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": { "@/*": ["src/*"] },
    "jsx": "react-jsx"
  },
  "include": ["src"]
}
`,
    })
  }

  files.push(
    {
      path: `vite.config.${sExt}`,
      content: `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'node:path'

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
})
`,
    },
    ...styleAndUiFiles(
      'vite',
      language,
      contentGlobs,
      'src/index.css',
      PLAIN_CSS,
      shadcn
    ),
    {
      path: 'index.html',
      content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${repoName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/${mainFile}"></script>
  </body>
</html>
`,
    },
    {
      path: '.gitignore',
      content: `node_modules
dist
dist-ssr
*.local
.DS_Store
.env*
!.env.example
npm-debug.log*
yarn-debug.log*
yarn-error.log*
`,
    },
    readme(repoName, meta.label, language, instructions, meta.runCommand, shadcn),
    {
      path: mainFile,
      content:
        language === 'ts'
          ? `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './index.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
)
`
          : `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './index.css'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>
)
`,
    },
    {
      path: `src/App.${cExt}`,
      content: pageContent({
        language,
        shadcn,
        note,
        componentName,
        fnName: 'App',
        importLine: `import ${componentName} from './components/${componentName}'`,
      }),
    },
    {
      path: `src/components/${componentName}.${cExt}`,
      content: componentSource,
    }
  )

  return files
}

function generateTanstack(input: GenCtx): RepoFile[] {
  const meta = getFramework('tanstack')
  const {
    repoName,
    componentName,
    componentSource,
    instructions,
    language,
    shadcn,
  } = input
  const note = commentBlock(instructions)
  const cExt = componentExt(language)
  const sExt = scriptExt(language)
  const mainFile = `src/main.${cExt}`
  const packages = mergeShadcnPackages(meta.packages, shadcn)
  const contentGlobs = ['./index.html', './src/**/*.{js,ts,jsx,tsx}']

  const files: RepoFile[] = [
    pkgJson(
      repoName,
      packages,
      language,
      {
        dev: 'vite',
        build: language === 'ts' ? 'tsc -b && vite build' : 'vite build',
        preview: 'vite preview',
      },
      { type: 'module' }
    ),
  ]

  if (language === 'ts') {
    files.push(
      {
        path: 'tsconfig.json',
        content: `{
  "compilerOptions": {
    "target": "ES2022",
    "useDefineForClassFields": true,
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "baseUrl": ".",
    "paths": { "@/*": ["src/*"] }
  },
  "include": ["src"]
}
`,
      },
      {
        path: 'src/vite-env.d.ts',
        content: `/// <reference types="vite/client" />
`,
      }
    )
  } else {
    files.push({
      path: 'jsconfig.json',
      content: `{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": { "@/*": ["src/*"] },
    "jsx": "react-jsx"
  },
  "include": ["src"]
}
`,
    })
  }

  const indexRouteBody = shadcn
    ? `${shadcnDemoImports()}
import { createFileRoute } from '@tanstack/react-router'
import ${componentName} from '@/components/${componentName}'

${shadcnDemoComponent()}
export const Route = createFileRoute('/')({
  component: HomePage,
})

function HomePage() {
  return (
    <main className="mx-auto min-h-screen max-w-3xl p-6">
      <ShadcnStarter />
      ${note}<${componentName} />
    </main>
  )
}
`
    : `import { createFileRoute } from '@tanstack/react-router'
import ${componentName} from '@/components/${componentName}'

export const Route = createFileRoute('/')({
  component: HomePage,
})

function HomePage() {
  return (
    <main className="mx-auto min-h-screen max-w-3xl p-6">
      ${note}<${componentName} />
    </main>
  )
}
`

  files.push(
    {
      path: `vite.config.${sExt}`,
      content: `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { TanStackRouterVite } from '@tanstack/router-plugin/vite'
import path from 'node:path'

export default defineConfig({
  plugins: [TanStackRouterVite({ autoCodeSplitting: true }), react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
})
`,
    },
    ...styleAndUiFiles(
      'tanstack',
      language,
      contentGlobs,
      'src/index.css',
      PLAIN_CSS,
      shadcn
    ),
    {
      path: 'index.html',
      content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${repoName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/${mainFile}"></script>
  </body>
</html>
`,
    },
    {
      path: '.gitignore',
      content: `node_modules
dist
.DS_Store
.env*
!.env.example
npm-debug.log*
yarn-debug.log*
yarn-error.log*
`,
    },
    readme(repoName, meta.label, language, instructions, meta.runCommand, shadcn),
    {
      path: mainFile,
      content:
        language === 'ts'
          ? `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { routeTree } from './routeTree.gen'
import './index.css'

const queryClient = new QueryClient()
const router = createRouter({
  routeTree,
  context: { queryClient },
})

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>
)
`
          : `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { routeTree } from './routeTree.gen'
import './index.css'

const queryClient = new QueryClient()
const router = createRouter({
  routeTree,
  context: { queryClient },
})

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>
)
`,
    },
    {
      path: `src/routeTree.gen.${sExt}`,
      content: `/* eslint-disable */
// Generated-style route tree for RepCN scaffolds.
// Running \`npm run dev\` with the TanStack router plugin will refresh this file.

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'

const IndexRouteWithChildren = IndexRoute

export const routeTree = rootRoute.addChildren([IndexRouteWithChildren])
`,
    },
    {
      path: `src/routes/__root.${cExt}`,
      content:
        language === 'ts'
          ? `import { Outlet, createRootRouteWithContext } from '@tanstack/react-router'
import type { QueryClient } from '@tanstack/react-query'

export const Route = createRootRouteWithContext<{
  queryClient: QueryClient
}>()({
  component: () => <Outlet />,
})
`
          : `import { Outlet, createRootRouteWithContext } from '@tanstack/react-router'

export const Route = createRootRouteWithContext()({
  component: () => <Outlet />,
})
`,
    },
    {
      path: `src/routes/index.${cExt}`,
      content: indexRouteBody,
    },
    {
      path: `src/components/${componentName}.${cExt}`,
      content: componentSource,
    }
  )

  return files
}

export function generateRepoFiles(input: GenerateInput): {
  repoName: string
  files: RepoFile[]
  framework: FrameworkId
  language: LanguageId
  shadcn: boolean
} {
  const framework: FrameworkId = input.framework || 'nextjs'
  const language: LanguageId = input.language || 'ts'
  const shadcn = Boolean(input.shadcn)
  const repoName = slugify(input.repoName || 'repcn-app')
  const componentName = extractComponentName(input.componentCode)
  const componentSource = ensureDefaultExport(
    input.componentCode,
    componentName
  )
  const instructions = (input.instructions || '').trim()
  const payload: GenCtx = {
    repoName,
    componentName,
    componentSource,
    instructions,
    language,
    shadcn,
  }

  const files =
    framework === 'vite'
      ? generateVite(payload)
      : framework === 'tanstack'
        ? generateTanstack(payload)
        : generateNextjs(payload)

  return { repoName, files, framework, language, shadcn }
}

export function summarizeRepo(files: RepoFile[]) {
  const encoder = new TextEncoder()
  return files.map((f) => ({
    path: f.path,
    bytes: encoder.encode(f.content).length,
  }))
}

export type TreeNode = {
  name: string
  path: string
  type: 'file' | 'folder'
  children?: TreeNode[]
}

/** Build a nested folder tree from flat file paths. */
export function buildFileTree(files: { path: string }[]): TreeNode[] {
  type Mutable = {
    name: string
    path: string
    type: 'file' | 'folder'
    children?: Map<string, Mutable>
  }

  const root = new Map<string, Mutable>()

  for (const file of files) {
    const parts = file.path.split('/')
    let current = root
    let pathSoFar = ''

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i]
      pathSoFar = pathSoFar ? `${pathSoFar}/${part}` : part
      const isFile = i === parts.length - 1

      if (!current.has(part)) {
        current.set(part, {
          name: part,
          path: pathSoFar,
          type: isFile ? 'file' : 'folder',
          children: isFile ? undefined : new Map(),
        })
      }

      const node = current.get(part)!
      if (!isFile) {
        if (!node.children) node.children = new Map()
        current = node.children
      }
    }
  }

  function toArray(map: Map<string, Mutable>): TreeNode[] {
    return [...map.values()]
      .map((node) => ({
        name: node.name,
        path: node.path,
        type: node.type,
        children: node.children ? toArray(node.children) : undefined,
      }))
      .sort((a, b) => {
        if (a.type !== b.type) return a.type === 'folder' ? -1 : 1
        return a.name.localeCompare(b.name)
      })
  }

  return toArray(root)
}
