import type { RepoFile } from '@/lib/github'

export type GenerateInput = {
  componentCode: string
  instructions?: string
  repoName?: string
}

function slugify(name: string) {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 40) || 'repcn-app'
  )
}

function extractComponentName(code: string): string {
  const named =
    code.match(/export\s+default\s+function\s+([A-Za-z0-9_]+)/)?.[1] ||
    code.match(/function\s+([A-Za-z0-9_]+)\s*\(/)?.[1] ||
    code.match(/const\s+([A-Za-z0-9_]+)\s*=/)?.[1]
  return named || 'GeneratedComponent'
}

function ensureDefaultExport(code: string, componentName: string): string {
  if (/export\s+default/.test(code)) return code.trim() + '\n'
  if (new RegExp(`function\\s+${componentName}\\b`).test(code) ||
    new RegExp(`const\\s+${componentName}\\b`).test(code)) {
    return `${code.trim()}\n\nexport default ${componentName}\n`
  }
  return `${code.trim()}\n\nexport default function ${componentName}() {\n  return null\n}\n`
}

export function generateRepoFiles(input: GenerateInput): {
  repoName: string
  files: RepoFile[]
} {
  const repoName = slugify(input.repoName || 'repcn-app')
  const componentName = extractComponentName(input.componentCode)
  const componentSource = ensureDefaultExport(
    input.componentCode,
    componentName
  )
  const instructions = (input.instructions || '').trim()

  const pageInstructions = instructions
    ? `\n{/* Instructions: ${instructions.replace(/\*\//g, '* /')} */}\n`
    : ''

  const files: RepoFile[] = [
    {
      path: 'package.json',
      content: JSON.stringify(
        {
          name: repoName,
          version: '0.1.0',
          private: true,
          scripts: {
            dev: 'next dev',
            build: 'next build',
            start: 'next start',
            lint: 'next lint',
          },
          dependencies: {
            next: '^15.1.0',
            react: '^19.0.0',
            'react-dom': '^19.0.0',
            sonner: '^1.7.0',
            'lucide-react': '^0.468.0',
          },
          devDependencies: {
            typescript: '^5.7.0',
            '@types/node': '^22.0.0',
            '@types/react': '^19.0.0',
            '@types/react-dom': '^19.0.0',
            tailwindcss: '^3.4.16',
            postcss: '^8.4.49',
            autoprefixer: '^10.4.20',
          },
        },
        null,
        2
      ) + '\n',
    },
    {
      path: 'tsconfig.json',
      content: `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`,
    },
    {
      path: 'next.config.ts',
      content: `import type { NextConfig } from 'next'

const nextConfig: NextConfig = {}

export default nextConfig
`,
    },
    {
      path: 'postcss.config.mjs',
      content: `/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}

export default config
`,
    },
    {
      path: 'tailwind.config.ts',
      content: `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

export default config
`,
    },
    {
      path: 'next-env.d.ts',
      content: `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`,
    },
    {
      path: '.gitignore',
      content: `# dependencies
/node_modules
/.pnp
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/versions

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem
.env*
!.env.example

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# typescript
*.tsbuildinfo
next-env.d.ts
`,
    },
    {
      path: 'README.md',
      content: `# ${repoName}

Generated by RepCN from a React component.

${instructions ? `## Instructions\n\n${instructions}\n\n` : ''}## Run

\`\`\`bash
npm install
npm run dev
\`\`\`
`,
    },
    {
      path: 'app/globals.css',
      content: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  color-scheme: light;
}

body {
  @apply min-h-screen bg-zinc-50 text-zinc-900 antialiased;
}
`,
    },
    {
      path: 'app/layout.tsx',
      content: `import type { Metadata } from 'next'
import { Toaster } from 'sonner'
import './globals.css'

export const metadata: Metadata = {
  title: '${repoName}',
  description: 'Generated by RepCN',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  )
}
`,
    },
    {
      path: 'app/page.tsx',
      content: `import ${componentName} from '@/components/${componentName}'

export default function HomePage() {
  return (
    <main className="mx-auto min-h-screen max-w-3xl p-6">
      ${pageInstructions}<${componentName} />
    </main>
  )
}
`,
    },
    {
      path: `components/${componentName}.tsx`,
      content: componentSource,
    },
  ]

  return { repoName, files }
}

export function summarizeRepo(files: RepoFile[]) {
  return files.map((f) => ({
    path: f.path,
    bytes: Buffer.byteLength(f.content, 'utf8'),
  }))
}
